[build]
  command = "dotnet publish CircuitBreakerDemo.Web/CircuitBreakerDemo.Web.csproj -c Release -o publish"
  publish = "publish/wwwroot"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200